# TCL File Generated by Component Editor 17.1
# Sun Mar 08 21:57:26 EDT 2026
# DO NOT MODIFY


# 
# eric_ip2 "eric_ip2" v1.0
#  2026.03.08.21:57:26
# 16 address APB
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module eric_ip2
# 
set_module_property DESCRIPTION "16 address APB"
set_module_property NAME eric_ip2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Custom Functions"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME eric_ip2
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL eric_ip2
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file eric_ip2.v VERILOG PATH eric_ip2.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point aps_s0
# 
add_interface aps_s0 apb end
set_interface_property aps_s0 associatedClock clock
set_interface_property aps_s0 associatedReset reset
set_interface_property aps_s0 ENABLED true
set_interface_property aps_s0 EXPORT_OF ""
set_interface_property aps_s0 PORT_NAME_MAP ""
set_interface_property aps_s0 CMSIS_SVD_VARIABLES ""
set_interface_property aps_s0 SVD_ADDRESS_GROUP ""

add_interface_port aps_s0 aps_s0_paddr paddr Input 6
add_interface_port aps_s0 aps_s0_psel psel Input 1
add_interface_port aps_s0 aps_s0_penable penable Input 1
add_interface_port aps_s0 aps_s0_pwrite pwrite Input 1
add_interface_port aps_s0 aps_s0_pwdata pwdata Input 32
add_interface_port aps_s0 aps_s0_prdata prdata Output 32
add_interface_port aps_s0 aps_s0_pready pready Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1

